[PAGE}:Cart
maxim-petrenko/techmart-ecommerce pull request #24
Opened 2021-10-30 02:22 UTC by Ordx

2021-10-30 07:59 UTC, Pavlo-Klymchuk requested changes

2021-10-30 07:59 UTC, Pavlo-Klymchuk commented on client/src/pages/Cart/styles.js
> +<<<<<<< HEAD
это конфликты, если я не ошибаюсь, посмотри у себя и если есть исправь

2021-10-31 23:30 UTC, Ordx commented on client/src/pages/Cart/styles.js
> +<<<<<<< HEAD
ок, убрал конфликты

2021-11-01 09:22 UTC, Pavlo-Klymchuk approved these changes

2021-11-01 11:01 UTC, daviddubliakov requested changes
нужно пофиксить форматирование

2021-11-01 11:01 UTC, daviddubliakov commented on client/src/pages/Cart/Cart.jsx
> +    const products = [
Нужно пофиксить выравнивание!

2021-11-01 11:01 UTC, daviddubliakov commented on client/src/pages/Cart/Cart.jsx
> +                                                    id={product.id}
тоже выравнивание

2021-11-01 11:01 UTC, daviddubliakov commented on client/src/pages/Cart/Cart.jsx
> +                        <Typography
тут тоже что-то не так с форматированием

2021-11-01 11:01 UTC, daviddubliakov commented on client/src/pages/Cart/CartItem/CartItem.jsx
> +                      id,
и тут

2021-11-05 12:25 UTC, Ordx commented on client/src/pages/Cart/Cart.jsx
> +                                                    id={product.id}
сделал

2021-11-06 07:52 UTC, Pavlo-Klymchuk approved these changes

2021-11-08 11:49 UTC, daviddubliakov commented on client/src/pages/Cart/CartItem/index.js
> +
Сделай файл CartItem как index.js и удали этот файл.

2021-11-08 11:49 UTC, daviddubliakov approved these changes

2021-11-08 11:50 UTC, merged