Feat/admin page
maxim-petrenko/techmart-ecommerce pull request #28
Opened 2021-11-05 13:53 UTC by bardovec

Adding admin page with form and introduce routing system

2021-11-06 08:01 UTC, Pavlo-Klymchuk requested changes

2021-11-06 08:01 UTC, Pavlo-Klymchuk commented on client/src/redux/actions/adminPageActions.js
> +// };
если не нужно, удали

2021-11-07 21:10 UTC, Pavlo-Klymchuk commented
конфликты

2021-11-08 12:13 UTC, bardovec commented on client/src/redux/actions/adminPageActions.js
> +// };
done

2021-11-08 12:13 UTC, bardovec commented on client/src/router/AdminWrapper.jsx
> +  //   console.log(isUserAdmin())
done

2021-11-08 14:41 UTC, Pavlo-Klymchuk approved these changes

2021-11-10 11:41 UTC, daviddubliakov approved these changes

2021-11-10 11:41 UTC, merged