[PAGE]: filter + products
maxim-petrenko/techmart-ecommerce pull request #29
Opened 2021-11-05 15:00 UTC by VDidov

Add filter page

2021-11-06 07:56 UTC, Pavlo-Klymchuk approved these changes

2021-11-08 07:42 UTC, daviddubliakov requested changes
Написал комменты

2021-11-08 07:42 UTC, daviddubliakov commented on client/src/components/common/ProductsFilter/ProductsFilter.jsx
> +          // getAriaValueText={valuetext}
убери коммент

2021-11-08 07:42 UTC, daviddubliakov commented on client/src/components/common/ProductsFilter/ProductsFilter.jsx
> +          // onChange={quantityChange}
убери коммент

2021-11-08 07:42 UTC, daviddubliakov commented on client/src/pages/Products/Products.jsx
> +import { useStyles } from "./styles";
стиили импортируются снизу

2021-11-08 07:42 UTC, daviddubliakov commented on client/src/components/common/ProductsItem/ProductsItem.jsx
>  import { useStyles } from "./styles";
стиили импортируются снизу

2021-11-09 21:13 UTC, VDidov commented on client/src/components/common/ProductsItem/ProductsItem.jsx
>  import { useStyles } from "./styles";
fix

2021-11-09 21:13 UTC, VDidov commented on client/src/pages/Products/Products.jsx
> +import { useStyles } from "./styles";
fix

2021-11-09 21:13 UTC, VDidov commented on client/src/components/common/ProductsFilter/ProductsFilter.jsx
> +          // onChange={quantityChange}
fix

2021-11-09 21:13 UTC, VDidov commented on client/src/components/common/ProductsFilter/ProductsFilter.jsx
> +          // getAriaValueText={valuetext}
fix

2021-11-09 21:13 UTC, VDidov commented on client/src/components/common/ProductsFilter/index.js
> +
fix

2021-11-09 21:13 UTC, VDidov commented on client/src/components/common/ProductsFilter/PopUpFilter/PopUpFilter.jsx
> +        aria-describedby="alert-dialog-slide-description"
fix

2021-11-09 21:13 UTC, VDidov commented on client/src/components/common/ProductsFilter/PopUpFilter/PopUpFilter.jsx
> +    setOpen(false);
fix

2021-11-09 21:13 UTC, VDidov commented on client/src/components/common/ProductsFilter/PopUpFilter/PopUpFilter.jsx
> +  const handleClickOpen = () => {
fix

2021-11-09 21:14 UTC, VDidov commented on client/src/components/common/Loader/index.js
> +
fix

2021-11-09 21:14 UTC, VDidov commented on client/src/components/common/Loader/Loader.jsx
> +      style={{ flexDirection: "column", alignItems: "center" }}
fix

2021-11-09 21:14 UTC, VDidov commented on client/src/components/common/Loader/Loader.jsx
> +      sx={{ display: "flex" }}
fix

2021-11-10 11:41 UTC, daviddubliakov approved these changes

2021-11-10 13:10 UTC, merged