[FEAT]: adds product list on main page
maxim-petrenko/techmart-ecommerce pull request #8
Opened 2021-10-01 15:30 UTC by anastasia-zastela

product list on main page added

2021-10-01 17:50 UTC, Pavlo-Klymchuk approved these changes

2021-10-01 18:03 UTC, Pavlo-Klymchuk approved these changes

2021-10-03 09:47 UTC, daviddubliakov requested changes
Оставил комменты. Проверь.

2021-10-03 09:47 UTC, daviddubliakov commented on client/src/pages/Main/Main.js
> -import img from '../iphone12.jpg'
картинки должны быть в public/images

2021-10-03 09:47 UTC, daviddubliakov commented on client/src/pages/Main/Main.js
> +import { useStyles } from './styles';
стили должны быть испортированы в конце через enter

2021-10-03 09:47 UTC, daviddubliakov commented on client/src/pages/Main/Main.js
> +import { CircularProgress, Grid, Typography } from '@material-ui/core';
отдели через enter импорты либ от компонентов

2021-10-03 09:47 UTC, daviddubliakov commented on client/src/pages/Main/Main.js
> +const loading = false;
убри эти проверки и констаны. Потом будет бекенд и добавим это все правильно.

2021-10-03 09:47 UTC, daviddubliakov commented on client/src/pages/Main/Main.js
> +        <ProductList products={products} />
Оставь только ProductList все остальное пока не имеет смысла

2021-10-03 09:47 UTC, daviddubliakov commented on client/src/pages/Main/styles.js
> +export const useStyles = makeStyles(() => ({
сделай useStyles как export default снизу

2021-10-03 16:03 UTC, anastasia-zastela commented on client/src/pages/Main/Main.js
> -import img from '../iphone12.jpg'
fixed

2021-10-03 16:03 UTC, anastasia-zastela commented on client/src/pages/Main/Main.js
> +import { useStyles } from './styles';
fixed

2021-10-03 16:03 UTC, anastasia-zastela commented on client/src/pages/Main/Main.js
> +import { CircularProgress, Grid, Typography } from '@material-ui/core';
fixed

2021-10-03 16:03 UTC, anastasia-zastela commented on client/src/pages/Main/Main.js
> +        <ProductList products={products} />
fixed

2021-10-03 16:04 UTC, anastasia-zastela commented on client/src/pages/Main/styles.js
> +export const useStyles = makeStyles(() => ({
fixed

2021-10-03 16:08 UTC, daviddubliakov requested changes
Написал по поводу одного фиксаю. Посмотри.

2021-10-03 16:08 UTC, daviddubliakov commented on client/src/pages/Main/Main.jsx
> +import React from 'react';
забыл сказать про названия файлов. Если ты например делаешь компоненет Main, то его главный файл не называй также, а index.jsx и когда где-то его импортироешь не обращаешся к файлу index а просто к папке.

2021-10-03 16:12 UTC, anastasia-zastela commented on client/src/pages/Main/Main.jsx
> +import React from 'react';
fixed

2021-10-05 06:58 UTC, daviddubliakov requested changes
Пофикси конфликт.

2021-10-15 09:56 UTC, daviddubliakov requested changes
Конфликты

2021-11-08 18:21 UTC, daviddubliakov approved these changes

2021-11-11 13:23 UTC, merged